package com.example;

import java.util.Date;
import java.util.function.Supplier;

import com.google.gson.Gson;

public class Event {
    private int reportId;
    private Date timestamp;
    private int metricId;
    private int metricValue;
    private String message;
    static int nextReporterID = 0;
    static int nextMetricID = 0;


    private Event(int reportId, Date timestamp, int metricId, int metricValue, String message) {
        this.reportId = reportId;
        this.timestamp = timestamp;
        this.metricId = metricId;
        this.metricValue = metricValue;
        this.message = message;
    }

    /**
     * Creats new event with uniuque metricId and reportId. messege generated by
     * suppliers of messages and metricValue
     * 
     * @param messageSupplier the messege supplier
     * @param metricValSupplier the matric value supplier
     * @return new generated dat
     */
    public static Event create(Supplier<String> messageSupplier,Supplier<Integer> metricValSupplier) {
        int nReportId = nextReporterID;
        int nMetricId = nextMetricID;
        Date nTimeStamp = new Date(System.currentTimeMillis());
        int nMetricValue = metricValSupplier.get();
        String nMessage = messageSupplier.get();
        nextReporterID++;
        nextMetricID++;
        return new Event(nReportId, nTimeStamp, nMetricId, nMetricValue, nMessage);
    }
    /**
     * Make Json String that represent the object
     */
    public String toJson(){
        Gson g = new Gson();
        return g.toJson(this);
    }
    
    /**
     * create event from object 
     * @param json the json string
     * @return new event that was generated from json string
     */
    public static Event createFromJson(String json){
        Gson g = new Gson();
        return g.fromJson(json, Event.class);
    }

    public int getReportId() {
        return this.reportId;
    }

    public Date getTimestamp() {
        return this.timestamp;
    }

    public int getMetricId() {
        return this.metricId;
    }

    public int getMetricValue() {
        return this.metricValue;
    }

    
    public String getMessage() {
        return this.message;
    }


}