package com.example;

import java.util.Date;
import java.util.function.Supplier;

public class Event {
    private int reportId;
    private Date timestamp;
    private int metricId;
    private int metricValue;
    private String message;
    static int nextReporterID = 0;
    static int nextMetricID = 0;

    public Event() {
    }

    private Event(int reportId, Date timestamp, int metricId, int metricValue, String message) {
        this.reportId = reportId;
        this.timestamp = timestamp;
        this.metricId = metricId;
        this.metricValue = metricValue;
        this.message = message;
    }

    /**
     * Generate new event with uniuque metricId and reportId. messege generated by
     * supplier
     * 
     * @param messageSupplier the messege generator
     * @return new generated dat
     */
    public static Event generateRandomEvent(Supplier<String> messageSupplier) {
        int nReportId = nextReporterID;
        int nMetricId = nextMetricID;
        Date nTimeStamp = new Date(System.currentTimeMillis());
        int nMetricValue = 0; // TODO: figure out metricValue
        String nMessage = messageSupplier.get();
        nextReporterID++;
        nextMetricID++;
        return new Event(nReportId, nTimeStamp, nMetricId, nMetricValue, nMessage);

    }

}