package com.example;

import java.util.Date;
import java.util.function.Supplier;

public class Event {
    private int reportId;
    private Date timestamp;
    private int metricId;
    private int metricValue;
    private String name;
    static int nextReporterID = 0;
    static int nextMetricID = 0;

    public Event() {
    }

    private Event(int reportId, Date timestamp, int metricId, int metricValue, String name) {
        this.reportId = reportId;
        this.timestamp = timestamp;
        this.metricId = metricId;
        this.metricValue = metricValue;
        this.name = name;
    }
    /**
     * Generate new event with uniuque metricId and reportId. messege generated by supplier
     * @param strSupplier the messege generator
     * @return
     */
    public static Event generateRandomEvent(Supplier<String> messegeSupplier) {
        int nReportId = nextReporterID;
        int nMetricID = nextMetricID;
        Date nTimeStamp = g
        nextReporterID++;
        nextMetricID++;
        


    }

   
}